Use a commit ID rather than a tag for Tesseract v5.2.0
This fixes an error I encountered when the Makefile tried to checkout
the commit after running `git fetch origin 5.2.0`:

```
error: pathspec '5.2.0' did not match any file(s) known to git
```

I'm not clear on why I didn't run into this issue when testing the
initial update to v5.2.0, but pointing to a specific commit is
preferable in any case in case the tag gets re-created.